// Code generated by "stringer -type Cat"; DO NOT EDIT.

package iracing

import "strconv"

const _Cat_name = "OvalRoadMudRX"

var _Cat_index = [...]uint8{0, 4, 8, 11, 13}

func (i Category) String() string {
	i -= 1
	if i < 0 || i >= Category(len(_Cat_index)-1) {
		return "Cat(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Cat_name[_Cat_index[i]:_Cat_index[i+1]]
}
