// Code generated by "stringer -type Category -type LicenseClass"; DO NOT EDIT.

package iracing

import "strconv"

const _LicenseClass_name = "RookieDCBAPro"

var _LicenseClass_index = [...]uint8{0, 6, 7, 8, 9, 10, 13}

func (i LicenseClass) String() string {
	i -= 1
	if i < 0 || i >= LicenseClass(len(_LicenseClass_index)-1) {
		return "LicenseClass(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _LicenseClass_name[_LicenseClass_index[i]:_LicenseClass_index[i+1]]
}
